### ISSUE TITLE
iCal Export doesn't properly parse Wiki Page URLs

### ISSUE THREAD

**Issue by MacLemon** [Metalab/mos#11]
Enter a Wiki Page with Spaces in the title.
MediaWiki does replace them with underscores.
iCal Export cuts off at the first space instead of replacing them with underscores.
This results in URLs in the iCal exported events that point to a defunct or a totally different wiki page.

**Comment by kelvan** [comment]
Same behaviour was in calendar view and project wikipages.
Needs tests.

**Comment by anlumo** [comment]
The colon in the HTTP URL is also urlencoded, which many clients can't cope with.

The URL should use https, not http.

**Comment by Hetti** [comment]
Hey @MacLemon , can you recheck the issue?
I check myself and can't reproduce it in the meantime!

Please check and close if it's now obsolete! Thanks

**Comment by Hetti** [comment]
Hey @MacLemon , can you recheck the issue?
I check myself and can't reproduce it anymore in the meantime!
Spaces get URL encoded now!

Please check and close if it's now obsolete! Thanks

**Comment by Hetti** [comment]
also the URL Issue should not be the case anymore @anlumo

**Comment by MacLemon** [comment]
What a nice case of issue necromancy. :-)
Is looking good for me at the moment. Should I find a way to resurrect the problem again, I'll open a new issue.
Thanks for all the fixes!
