### ISSUE TITLE
Add support for web-based self-service password reset

### ISSUE THREAD

**Issue by thp** [Metalab/mos#12]
The MOS should have the option in the login page to reset forgotten user passwords, and mail a new one to the e-mail address listed in the database.

Use case:
1. User has forgotten her password

Expected result:
1. User can click on "forgotten password" on login page
2. User enters their username and/or e-mail address
3. MOS sends an e-mail with a confirmation link (no auto-reset)
4. When confirmation link is clicked, MOS generates and mails new password

Actual result (metalab.at-specific):
1. User needs to send e-mail to core@
2. Admins manually reset password

Additional comments:
The confirmation link is important to avoid problems with people randomly resetting other users' passwords. Ideally step 2 in "Expected result" should also have a captcha.

**Comment by kelvan** [comment]
Using username and email should be enough to avoid bots imo
Maybe show set new password instead of generating a new password
or set password unusable using the link in the email and force to set a new one.

**Comment by hop** [comment]
Updating `members/urls.py` with

    -    url(r'^login/?$', 'django.contrib.auth.views.login', {'template_name': 'members/member_login.html'}, name='login'),
    -    url(r'^logout/?$', 'django.contrib.auth.views.logout', name='logout'),
    +    url('^', include('django.contrib.auth.urls')),

is almost enough.

Several templates have to be customized and the link to the login page after a successful password reset is wrong (`/login/` instead of `/member/login/`, I think)

Token generation and email dispatch seem to work correctly.

Test cases for MOS specific URLs and stuff would be nice ;)

**Comment by Hetti** [comment]
thanks  @hop that you added early 2017 the password reset :heart: 
with commit https://github.com/Metalab/mos/commit/232bf60a5b341350f44a5422e8b0e9c7de5c1cd0
