### ISSUE TITLE
Redirect after creating an event sends the user to the new homepage instead of the MOS root URL

### ISSUE THREAD

**Issue by ralokt** [Metalab/mos#156]
Steps to reproduce:
 - navigate to MOS root url
 - click "Create new Event" in the sidebar
 - fill in info
 - click "Create"

Expected behavior: be redirected to MOS root
Actual behavior: be redirected to root URL of instance domain

**Comment by Hetti** [comment]
this behavior should be now changed with commit 84c96c592537aacba121edee8dd69f29376f5a88 ; instead a message appears next to the button with "saved" as status after pressing the button to create an evenet

can you please verify now @ralokt ?
