### ISSUE TITLE
Redirect after login sends the user to the new homepage instead of the MOS root URL

### ISSUE THREAD

**Issue by ralokt** [Metalab/mos#157]
like #156 but for logging in - this appears to be a pattern

**Comment by Hetti** [comment]
https://github.com/Metalab/mos/blob/9abb6c90eb75550e4bffbb3a1d1c13b243fbe31c/mos/settings/common.py#L123

**Comment by ppiro** [comment]
I just tried
`LOGIN_REDIRECT_URL = '/mos'`
locally and that worked for me. My first try was with a slash at the end, which did not work.

**Comment by Hetti** [comment]
I monkey patched it on live and it didn't worked there.
so I failed to test it properly - just tried again locally and it works :-)
