### ISSUE TITLE
Required Wikipage should be checked for existence.

### ISSUE THREAD

**Issue by MaxValue** [Metalab/mos#166]
Possible solutions:

1. In [`update_event()` in cal/views.py](https://github.com/Metalab/mos/blob/c7420aeb145badb0d127c6c9dbcf3cff21b07d0f/cal/views.py#L149) add a check which uses a similar function as [`get_wiki_article()` in sources/management/commands/jour_fixe_reminder.py](https://github.com/Metalab/mos/blob/c7420aeb145badb0d127c6c9dbcf3cff21b07d0f/sources/management/commands/jour_fixe_reminder.py#L19) to get the wiki article. How to display the error to the user?
2.  Extend the [`EventForm` in cal/forms.py](https://github.com/Metalab/mos/blob/c7420aeb145badb0d127c6c9dbcf3cff21b07d0f/cal/forms.py#L9) to include a check for this which works as above.

**Comment by ralokt** [comment]
I'm not sure this is a great idea, tbh. What about a workflow like
 - create event with nonexistent wiki page
 - click broken link
 - get asked if you want to create this page
 - create this page
