### ISSUE TITLE
Calendar view should only display the list of events for the current month

### ISSUE THREAD

**Issue by MaxValue** [Metalab/mos#168]
The calendar view (when clicking on "Kalender" on the new frontpage or when clicking on "Events" on the old front page) points to a calendar visualization. Underneath this calendar visualization is a list of calendar events spanning from the current date (?) to about 1 year into the future.

Change this to only display the list of calendar events for the currently displayed month?

**Comment by eest9** [comment]
Which calendar view are you referring to?

**Comment by MaxValue** [comment]
I added more details! Thanks for the follow up question!

**Comment by eest9** [comment]
I think it should only be reduced when we implement a search function for events. I find myself often on this page using ctrl+f to find details about when which future event will happen again

**Comment by MaxValue** [comment]
The problem with this is:

[The list is generated here](https://github.com/Metalab/mos/blob/69666407917cc36b2da751269d77265a490bb3e2/cal/views.py#L81). BUT: If you click on another month in this calendar view, only the list of events for the selected month will be listed! So this is actually already implemented, but the frontpages do not link to the current month, which makes kinda sense.

So there are 3 solutions:

- Change the links (inside the frontpages) to the calendar view for the current month (kinda hackish)
- Add another route (something like `/calendar/now`) which points to the view for the current month and change the links in the front pages to that.
- Have the route `/calendar` only display the current month, but add another route `/calendar/all` which displays the complete list like we have now.
