### ISSUE TITLE
Move new frontpage to MOS as endpoint

### ISSUE THREAD

**Issue by MaxValue** [Metalab/mos#188]
[This url route](https://github.com/Metalab/mos/blob/c7420aeb145badb0d127c6c9dbcf3cff21b07d0f/mos/urls.py#L26) needs to be changed to point to the static file.

**Comment by Hetti** [comment]
was meinst du damit genau?

**Comment by MaxValue** [comment]
Naja, so hätten wir den gesamten Website-Code in einer Repo.

Mein Plan wäre, die Datei einfach "as is" zu den static files zu schieben und an den Endpoint zu hängen. Zusätzlich würde ich eine gut sichtbare Notiz in das Readme packen, sodass Menschen, die nur an der Frontpage arbeiten wollen, diese einfach finden können.

**Comment by luto** [comment]
Aber (erreichtes) Ziel des Neue-Website-Projekts war ja genau die ganze Webseite eben nicht in einem Repo zu haben, sondern in getrennten Projekten.

**Comment by MaxValue** [comment]
Aber welcher Vorteil soll dadurch erzielt werden?

**Comment by luto** [comment]
Die Projekte können unabhängig umstrukturiert/neugestartet werden und die Hürde einen Haufen HTML-Files zu editieren/testen ist niedriger als Django. Beides soll für mehr Updates für die Webseite und damit bessere Webseite sorgen. Klappt bis jetzt gut mit kleineren Änderungen von random membern.

Da die Trennung Ziel des Projekts war mach ich das hier mal als "works as intended" zu.

**Comment by MaxValue** [comment]
Das klingt sehr plausibel. Gut, dass wir das mal öffentlich ausdiskutiert haben.
