### ISSUE TITLE
Mandats-ID nicht verpflichtend bei aktiviertem Bankeinzug

### ISSUE THREAD

**Issue by regendrogenbogen** [Metalab/mos#202]
Wird der Bankeinzug aktiviert, kann ein Mitglied auch ohne eingetragene gespeichert werden. Dann funktioniert der Sepa-XML generator allerdings nicht.

**Comment by regendrogenbogen** [comment]
Felder die gechecked werden sollten:
- Bank collection mode
- Bank account owner
- Bank account iban
- Bank account bic
- Bank account mandate reference
- Bank account date of signing

**Comment by regendrogenbogen** [comment]
Lösungsidee: wenn das Feld leer ist, einfach User-ID rein schreiben beim Speichern

**Comment by qbe** [comment]
alternativ: wenn der abbucher ausgelöst wird und nix steht im Feld, die User-ID nehmen, und evtl. ins Feld eintragen
