### ISSUE TITLE
Erweitere iButtons für Laser etc.

### ISSUE THREAD

**Issue by anlumo** [Metalab/mos#215]
* Generalisierung der Laserauth auf andere Dinge (`has_lazzzor_privileges`)
	* Drehbank, Elektronikkammerl, Prusa XL, Eingangstür, etc etc etc
	* needs Admin interface
		* neue Privileges anlegen, mit username+passwort
		* Checkbox pro User: hat Privilege
	* Anzeige auf eigenen Userseite, welche Privileges der User hat
* Wie iButton ID vom MOS abfragen?
	* CSV: `ibuttonid,username\n`
	* getrennter Endpoint pro Freischaltesystem
	* https://metalab.at/member/privilegelist?privilege=prusaxl mit BASIC AUTH
	* Userdaten Privilege-spezifisch im Admin-Interface

**Comment by qbe** [comment]
heisst das, das MOS liefert eine Liste von ibuttonIDs aus ?

**Comment by luto** [comment]
Wie aktuell bei der Tür auch, ja.

**Comment by qbe** [comment]
wieso nicht gehasht & gesalzen ?

**Comment by luto** [comment]
Geht auch, ist aber bei der Art wie wir die iButtons verwenden alles nur security theater.

**Comment by qbe** [comment]
eh. Um das zu improven bräuchten wir implementierte Crypto in der Door, und dann müssen die User jeweils einmal bei einem Gerät vorbei was das signing oder wie auch immer macht.

Ich fänds halt komisch bervor wir sowas haben die IDs (die ja momentan das einzige Secret sind) weiter zu verteilen.

**Comment by qbe** [comment]
challenge / response funktioniert bei der Door halt nicht weil die das cachen muss.

**Comment by luto** [comment]
Was anderes als die IDs haben wir nicht, also werden wir bei Laser und Prusa XL mit den IDs arbeiten müssen.

**Comment by qbe** [comment]
Deswegen mein Vorschlag sie zu hashen. Damit es nicht noch mehr Punkte gbit wo die Secrets im Klartext abgegriffen werden können.

**Comment by luto** [comment]
Ich bau kein eigenes custom challenge-response auf dem wackeligen ID-System auf. Wenn die Anforderung ist, dass man iButtons nicht clonen können darf, bitte auf das challenge-response, das die Dinger eh schon können, umsteigen. Das ist aber out of scope für dieses Issue.

**Comment by anlumo** [comment]
Naja, salten und hashen kann man ohne challenge/response auch, so wie /etc/shadow auf Linux halt.

**Comment by qbe** [comment]
Das war genau was ich meinte.

**Comment by anlumo** [comment]
Der Search Space ist halt so klein, dass es vielleicht nicht viel Sinn macht, nachdem man den vermutlich in Sekunden komplett durchsuchen kann.

**Comment by luto** [comment]
Genau das, ja :) aber ich wollte jetzt hier nicht den kompletten Angriff öffentlich skizzieren 😅 so einfach wie er ist, ist es aber vielleicht auch egal.
