### ISSUE TITLE
Updating/deleting an event that is already deleted leads to server errors

### ISSUE THREAD

**Issue by hop** [Metalab/mos#24]
Since the edit menu stays on screen without feedback after deleting an event, this is a frequent issue.

**Comment by kelvan** [comment]
Nope not fixed

**Comment by kelvan** [comment]
But this should do it 2924fa3191f596387193c904ec051d75daf7176b

**Comment by Hetti** [comment]
fixed since years, while testing just to be sure I found a broken procedure calling a non existent calender-content endpoint :D 
fixed: 4c0c35d892848e4180a5d703ce16e65799288fde
