### ISSUE TITLE
Jour Fixe should not require a Wiki page to create calendar entry

### ISSUE THREAD

**Issue by regendrogenbogen** [Metalab/mos#258]
The workflow for making a year of JFs in the calendar was:
* create first entry, link non-existing wiki page
* modify date, crate 24 JFs
* be done in 10 minutes
* no problem
when it is time for another JF:
* click link in calendar
* create Jeff page from template
* no problem

Now this isn't possible. which makes ripper sad

**Comment by luto** [comment]
18f9f0cc0e450a3ab36419adbc293d536931307f
