### ISSUE TITLE
"On intern list" email field does not accept new nTLD domains

### ISSUE THREAD

**Issue by simonrepp** [Metalab/mos#31]
Says "Enter a valid e-mail address." to my valid email address w/ new shiny and super long domain ending. Probably some regex foo that checks for length or a field validation against a white-list, either should be dropped.

Edit: Same bug for the standard email field.

**Comment by kelvan** [comment]
mos uses EmailField for that, it should be fixed in new Django versions

**Comment by Hetti** [comment]
Should work now, if not please reopen :)
