### ISSUE TITLE
Updating a calender event should give some response

### ISSUE THREAD

**Issue by queltos** [Metalab/mos#32]
When updating a calender event after pressing the "update" button there is no response and hence unclear if it succeeded or not. Button is working though, only feedback is missing.

**Comment by Hetti** [comment]
after finally nearly 7 years this got Fixed at Hackathon 15 @metalab :-)

Thanks to @ppiro and maxvalue

fixed with commit 84c96c592537aacba121edee8dd69f29376f5a88
