### ISSUE TITLE
Calender Entrys should display room on overview page

### ISSUE THREAD

**Issue by norpol** [Metalab/mos#39]
I'm not sure how difficult it is to implement: But at the moment it's 'hard' for people to tell in which room events are at the overview page http://metalab.at/calendar/
Scrolling down to see the additional detail is not user friendly. :)

**Comment by kelvan** [comment]
maybe some icons/colours for the rooms would be a simple way to implement this, or view a shortcode after the event name

**Comment by norpol** [comment]
I'd prefer shortcuts, with link to the rooms:
 - WEL https://metalab.at/wiki/WEL
 - HM https://metalab.at/wiki/Heavy_Machinery
 - LG https://metalab.at/wiki/Lounge
 - HR https://metalab.at/wiki/Hauptraum
 - Bib https://metalab.at/wiki/Bibliothek
 - FL https://metalab.at/wiki/Fotolab

**Comment by kelvan** [comment]
Tried to understand the templates yesterday, I still have no idea where what is rendered.
It's also not good to add database fields until 1.8 is deployed on the Metalab server.
But if I find out where this stuff get rendered I can add some autogenerated (probably ugly) shortcut.

**Comment by luto** [comment]
room is shown on hover
