### ISSUE TITLE
Calendar feed does not show in-progress events

### ISSUE THREAD

**Issue by thp** [Metalab/mos#4]
Looking at the file:

https://github.com/Metalab/mos/blob/django_1_4_compatibility/cal/feeds.py

The query uses: ```startDate__gte=datetime.datetime.now()```

This works fine, but does not show events that have started in the past, but for which the end time has not been reached yet. I propose that the query is updated to something like that:

```(endDate IS NULL AND startDate >= now) OR (endDate >= now)```

**Comment by kelvan** [comment]
Should be fixed by pull request, needs tests to prove
