### ISSUE TITLE
Fix csrf_token errors

### ISSUE THREAD

**Issue by kelvan** [Metalab/mos#52]
There are various csrf_token errors when using ajax with POST.
At least when deleting events.

**Comment by kelvan** [comment]
Fixed part of the problem: a69bee825c4173d3957db90725a34d0cefb1284e

Second Ajax call tried to get updated event list as POST without csrftoken.
Since the call just get information I changed the method to GET.

**Comment by kelvan** [comment]
Second fix: dcd19e4dfa5c7f6d3dc79b66635b5752350f80f3

getCookie was unable to find csrftoken in cookies if it wasn't the first value, because there is a whitespace after the first ";".
" csrftoken=" vs "csrftoken="

**Comment by kelvan** [comment]
Still problems with list refresh afterwards

**Comment by luto** [comment]
There are currently no reports of csrf errors. If one shows up, open a new issue.
