### ISSUE TITLE
'pip install -r requirements.txt' fails

### ISSUE THREAD

**Issue by rponline** [Metalab/mos#53]
I just tried to install a test instance of mos on my local Debian 7 machine.

Steps 1-4 are working just fine.
But this one fails:
`5. Install dependencies: pip install -r requirements.txt`

Log:
[pip.log](https://github.com/Metalab/mos/files/58130/pip.txt)

**Comment by rponline** [comment]
after installing following packages (apt-get install), it works:
libexpat1-dev libpython-dev libpython2.7-dev python-dev python-setuptools python2.7-dev
I don't know which one of those did the job.

Oh .. and: Also "pip install -r requirements-dev.txt" is requied to pass step 7 in HACKING.

**Comment by norpol** [comment]
=) Great to hear!

**Comment by rponline** [comment]
Okey, i just tried to reconstruct what i did there ... 

Dependencies for Pillow (which is a dependency of mos) on a debian system, which are not installed by default:
* gcc
* libpython-dev

Should i add this to the File "HACKING"?

**Comment by hex2a** [comment]
i'd recommend to use vagrant as it will setup (most) dependencies using the provision_vagrant.yml ansible playbook
