### ISSUE TITLE
display who created an event

### ISSUE THREAD

**Issue by wilhelmy** [Metalab/mos#56]
We had no idea who to contact for a colliding event this week. It would be good to display the MOS username of the user who created an event so people know who to contact in case of questions.

**Comment by wilhelmy** [comment]
Because Hetti pointed out that my bug report is ambiguous, I meant the main page.

Screenshot:  <img src="http://barfooze.de/i/fukushima-201602121413.png">

**Comment by wilhelmy** [comment]
Is this live? I can't see who created an event.

I actually meant to include it in the calendar entry, not the edit view, because people might want to contact the person who registered an event for organizational reasons.

**Comment by Hetti** [comment]
This feature was just implemented with commit [@49637f990bf0a4d398ca863928fa7d78f2923af5
](https://github.com/Metalab/mos/commit/49637f990bf0a4d398ca863928fa7d78f2923af5)
