### ISSUE TITLE
 Kalender Template weist noch auf Raucherraum Lounge hin 

### ISSUE THREAD

**Issue by norpol** [Metalab/mos#60]
Via. sonstwer
Wenn man auf
​https://metalab.at/calendar/
ein Event hinzufügt gibt es die Auswahlmöglichkeit
Lounge (Raucherbetrieb) +
Lounge (Nichtraucherbetrieb)

die sollten gemerged werden, ich weiß halt nicht wie.

**Comment by hex2a** [comment]
das sinnvollste wäre vermutlich die id von den events mit "Lounge (Raucherbetrieb)" auf die von "Lounge (Nichtraucherbetrieb)" zu ändern und den namen von "Lounge (Nichtraucherbetrieb)" auf "Lounge" oÄ zu ändern.

Ansonsten könnte man die location(s) im django admin interface löschen, damit wären aber die zugehörigen Events auch weg.

**Comment by Hetti** [comment]
Es existiert mittlerweile nur noch die Kategorie `Lounge`

Ich weiß nicht wie das am Ende gelöst wurde. Somit schließe ich das Issue.
